### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by tyrann0us** [pedroelsner/force-regenerate-thumbnails#2]
Please read the following support threads:
- https://wordpress.org/support/topic/incompatible-with-php-7-8
- https://wordpress.org/support/topic/please-fix-deprecated-class-constructor
- https://wordpress.org/support/topic/compatible-with-php-7-11

The plugin is not compatible with PHP 7. Please update it.
Maybe https://github.com/plaidpowered/force-regenerate-thumbnails helps.

Thanks!

**Comment by PedroBegosso** [comment]
Fixed.
